### PR TITLE
Fix implementations of embedded_io::Write for UartPeripheral

### LINKED ISSUE #840: Our implementation of embedded_io::Write is wrong
See https://github.com/rp-rs/rp-hal/pull/837#issuecomment-2305371353

* [x] RP2040 HAL (https://github.com/rp-rs/rp-hal/pull/838)
* [ ] RP235x HAL

### PR DESCRIPTION
**Pull request by jannic**
Fixes #840

### CODE REVIEW

File: rp2040-hal/src/uart/peripheral.rs [hunk 1]
```diff
@@ -504,8 +504,8 @@ impl<D: UartDevice, P: ValidUartPinout<D>> embedded_io::ReadReady
 
 impl<D: UartDevice, P: ValidUartPinout<D>> embedded_io::Write for UartPeripheral<Enabled, D, P> {
     fn write(&mut self, buf: &[u8]) -> Result<usize, Self::Error> {
-        self.write_full_blocking(buf);
-        Ok(buf.len())
+        let remaining = nb::block!(super::writer::write_raw(&self.device, buf)).unwrap(); // Infallible
```
Comment (thejpster) [inline rp2040-hal/src/uart/peripheral.rs:507]: Might be worth repeating the embedded_io::Write rules here ("If the writer is not currently ready to accept more bytes (for example, its buffer is full), this function blocks until it is ready to accept least one byte.")

Comment (thejpster) [reply rp2040-hal/src/uart/peripheral.rs:507]: and that write_raw only blocks if the FIFO is full and nothing is written to it.

**Review by thejpster — APPROVED** [review]
Looks technically correct, but some comments might help the next person who looks at this :)
